### ISSUE TITLE
Does it work in the browser replacing the fetch api?

### ISSUE THREAD

**Issue by ricky11** [zeit/fetch-retry#8]
Can i add this to my client side application ?Can i use it to replace fetch?
I dont need node-fetch in as the browser already has the built in fetch.

**Comment by niftylettuce** [comment]
this package uses async/await and other syntax that may not be browser compatible, so no

**Comment by OlliV** [comment]
Correct, the `@zeit/fetch.*` modules aren't written in browser compatibility in mind.
